### ISSUE TITLE
Error in Latest versions (3.0.1)

### ISSUE THREAD

**Issue by cheeaun** [lottie-react-native/lottie-react-native#511]
From the [changelog](https://github.com/react-native-community/lottie-react-native/blob/master/CHANGELOG.md), version 3.0.0 and 3.0.1 are released. On [npm](https://www.npmjs.com/package/lottie-react-native), both versions are not available.

Any plans on publishing?

**Comment by owinter86** [comment]
It would be good to get these released to npm as the build gradle update changing the react native dependency from `compileOnly` to `implementation` fixes the error when running the jettifier post install script which has is the preferred method to migrate to androidX and RN 0.60.

https://github.com/react-native-community/react-native-maps/issues/2940

**Comment by emilioicai** [comment]
I'm having some issues building I want to make sure they are fixed before publishing. Hopefully 3.0.1 should be on npm later today. Sorry for the confusion

**Comment by emilioicai** [comment]
Done! @owinter86 @cheeaun Could you guys do me a favor and test if everything is working fine for you? I think I managed to fix all the issues but it would be great to have a some other real projects running `lottie-react-native` 3.0.1 to confirm everything is OK

**Comment by StanislavMayorov** [comment]
@emilioicai 
I have pod install error:
```
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
      lottie-ios (~> 3.0.4)
```
lottie-react-native `3.0.1`. I think there's the error because pacakge.json dependency lottie-ios 3.0.3

**Comment by alimek** [comment]
I have different problem:
```
unknown>:0: error: filename "TextCompositionLayer.swift" used twice: 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift' and 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
```

I have linked the `ios-lottie` and `lottie-react-native` manually

**Comment by mysport12** [comment]
@StanislavMayorov I can confirm that the pod install issue is due to the incorrect lottie-ios version specified in the package.json file. Should be 3.0.3 not 3.0.4.

**Comment by mysport12** [comment]
@StanislavMayorov Was able to workaround the issue for now by switching

`pod 'lottie-ios', :path => '../node_modules/lottie-ios'`

to 

`pod 'lottie-ios', '~> 3.0.4'`

in my Podfile. Hope that helps

**Comment by LaurieWilliamsNZ** [comment]
Followed your advice @StanislavMayorov 

I can now install the pod but getting `
The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

**Comment by LaurieWilliamsNZ** [comment]
Adding `use_modular_headers!` to the podfile allows the pods to be installed correctly. Thanks again @StanislavMayorov

**Comment by lyqht** [comment]
Adding `use_modular_headers` allows the pods to be installed correctly, but when building the app, i got the following error

```
⚠️  ld: directory not found for option '-L/Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/ios/build/dsPlayground/Build/Products/Debug-iphonesimulator/React'
⚠️  ld: directory not found for option '-L/Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/ios/build/dsPlayground/Build/Products/Debug-iphonesimulator/yoga'
⚠️  ld: Could not find auto-linked library 'swiftCoreFoundation'
⚠️  ld: Could not find auto-linked library 'swiftQuartzCore'
⚠️  ld: Could not find auto-linked library 'swiftCore'
⚠️  ld: Could not find auto-linked library 'swiftCoreGraphics'
⚠️  ld: Could not find auto-linked library 'swiftObjectiveC'
⚠️  ld: Could not find auto-linked library 'swiftDispatch'
⚠️  ld: Could not find auto-linked library 'swiftSwiftOnoneSupport'
⚠️  ld: Could not find auto-linked library 'swiftDarwin'
⚠️  ld: Could not find auto-linked library 'swiftUIKit'
⚠️  ld: Could not find auto-linked library 'swiftCoreImage'
⚠️  ld: Could not find auto-linked library 'swiftFoundation'
⚠️  ld: Could not find auto-linked library 'swiftMetal'
⚠️  ld: Could not find auto-linked library 'swiftCoreLocation'

❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening dsPlayground.xcworkspace

** BUILD FAILED **


The following commands produced analyzer issues:
        Analyze /Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/node_modules/react-native/ReactCommon/jsi/jsi.cpp normal x86_64
        Analyze /Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
        Analyze /Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
        Ld /Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/ios/build/dsPlayground/Build/Products/Debug-iphonesimulator/dsPlayground.app/dsPlayground normal x86_64
(1 failure)
```

**Comment by DaiYz** [comment]
@lyqht  same issue

**Comment by xks19943** [comment]
@lyqht  How do you solve this problem?  tanks

**Comment by xks19943** [comment]
@lyqht  hello, i find the way.  https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios/53101587#   i use second way

**Comment by emilioicai** [comment]
Guys, I just released 3.0.2 fixing the lottie-ios 3.0.3 dependency issue but I'm afraid there are more issues, specially when using RN 0.60.0. I would really appreciate if you guys could send any issues you are facing, including versions of RN and lottie-react-native.

Thanks!

**Comment by Hiro5409** [comment]
@emilioicai 
After upgrade to 3.0.2, the error still exists… 😭 
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

RN version: 0.59.10
lottie-react-native: 3.0.2

**Comment by pianoman730** [comment]
I'm getting this still:
```
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
      lottie-ios (~> 3.0.4)
```
I then change this 
`pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
to
`pod 'lottie-ios', '~> 3.0.4'`
and get this:
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```
Putting `:modular_headers => true` on `pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'` gives the same error.
Putting `use_modular_headers!` at the top of the pod file, `pod install` runs successfully. But when I build it, I get additional errors related to RCTImageLoader.

**Comment by tokinonagare** [comment]
> I have different problem:
> 
> ```
> unknown>:0: error: filename "TextCompositionLayer.swift" used twice: 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift' and 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift'
> <unknown>:0: note: filenames are used to distinguish private declarations with the same name
> ```
> 
> I have linked the `ios-lottie` and `lottie-react-native` manually

I solved by this patch.

`diff --git a/node_modules/lottie-ios/Lottie.xcodeproj/project.pbxproj b/node_modules/lottie-ios/Lottie.xcodeproj/project.pbxproj
index d6c2aa0..f6aecc8 100644
--- a/node_modules/lottie-ios/Lottie.xcodeproj/project.pbxproj
+++ b/node_modules/lottie-ios/Lottie.xcodeproj/project.pbxproj
@@ -168,7 +168,6 @@
 		486E8830220B78E4007CD915 /* PointValueProvider.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E871E220B78BF007CD915 /* PointValueProvider.swift */; };
 		486E8831220B78E4007CD915 /* CompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8722220B78BF007CD915 /* CompositionLayer.swift */; };
 		486E8832220B78E4007CD915 /* NullCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8723220B78BF007CD915 /* NullCompositionLayer.swift */; };
-		486E8833220B78E4007CD915 /* TextCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8724220B78BF007CD915 /* TextCompositionLayer.swift */; };
 		486E8834220B78E4007CD915 /* SolidCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */; };
 		486E8835220B78E4007CD915 /* PreCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8726220B78BF007CD915 /* PreCompositionLayer.swift */; };
 		486E8836220B78E4007CD915 /* ImageCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */; };
@@ -285,7 +284,6 @@
 		486E88A5220B78F4007CD915 /* PointValueProvider.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E871E220B78BF007CD915 /* PointValueProvider.swift */; };
 		486E88A6220B78F4007CD915 /* CompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8722220B78BF007CD915 /* CompositionLayer.swift */; };
 		486E88A7220B78F4007CD915 /* NullCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8723220B78BF007CD915 /* NullCompositionLayer.swift */; };
-		486E88A8220B78F4007CD915 /* TextCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8724220B78BF007CD915 /* TextCompositionLayer.swift */; };
 		486E88A9220B78F4007CD915 /* SolidCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */; };
 		486E88AA220B78F4007CD915 /* PreCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8726220B78BF007CD915 /* PreCompositionLayer.swift */; };
 		486E88AB220B78F4007CD915 /* ImageCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */; };
@@ -406,7 +404,6 @@
 		486E891E220B78FF007CD915 /* PointValueProvider.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E871E220B78BF007CD915 /* PointValueProvider.swift */; };
 		486E891F220B78FF007CD915 /* CompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8722220B78BF007CD915 /* CompositionLayer.swift */; };
 		486E8920220B78FF007CD915 /* NullCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8723220B78BF007CD915 /* NullCompositionLayer.swift */; };
-		486E8921220B78FF007CD915 /* TextCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8724220B78BF007CD915 /* TextCompositionLayer.swift */; };
 		486E8922220B78FF007CD915 /* SolidCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */; };
 		486E8923220B78FF007CD915 /* PreCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8726220B78BF007CD915 /* PreCompositionLayer.swift */; };
 		486E8924220B78FF007CD915 /* ImageCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */; };
@@ -523,7 +520,6 @@
 		486E8993220B790E007CD915 /* PointValueProvider.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E871E220B78BF007CD915 /* PointValueProvider.swift */; };
 		486E8994220B790E007CD915 /* CompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8722220B78BF007CD915 /* CompositionLayer.swift */; };
 		486E8995220B790E007CD915 /* NullCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8723220B78BF007CD915 /* NullCompositionLayer.swift */; };
-		486E8996220B790E007CD915 /* TextCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8724220B78BF007CD915 /* TextCompositionLayer.swift */; };
 		486E8997220B790E007CD915 /* SolidCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */; };
 		486E8998220B790E007CD915 /* PreCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8726220B78BF007CD915 /* PreCompositionLayer.swift */; };
 		486E8999220B790E007CD915 /* ImageCompositionLayer.swift in Sources */ = {isa = PBXBuildFile; fileRef = 486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */; };
@@ -673,7 +669,6 @@
 		486E871E220B78BF007CD915 /* PointValueProvider.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = PointValueProvider.swift; sourceTree = "<group>"; };
 		486E8722220B78BF007CD915 /* CompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = CompositionLayer.swift; sourceTree = "<group>"; };
 		486E8723220B78BF007CD915 /* NullCompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = NullCompositionLayer.swift; sourceTree = "<group>"; };
-		486E8724220B78BF007CD915 /* TextCompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = TextCompositionLayer.swift; sourceTree = "<group>"; };
 		486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SolidCompositionLayer.swift; sourceTree = "<group>"; };
 		486E8726220B78BF007CD915 /* PreCompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = PreCompositionLayer.swift; sourceTree = "<group>"; };
 		486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ImageCompositionLayer.swift; sourceTree = "<group>"; };
@@ -991,7 +986,6 @@
 			children = (
 				486E8722220B78BF007CD915 /* CompositionLayer.swift */,
 				486E8723220B78BF007CD915 /* NullCompositionLayer.swift */,
-				486E8724220B78BF007CD915 /* TextCompositionLayer.swift */,
 				486E8725220B78BF007CD915 /* SolidCompositionLayer.swift */,
 				486E8726220B78BF007CD915 /* PreCompositionLayer.swift */,
 				486E8727220B78BF007CD915 /* ImageCompositionLayer.swift */,
@@ -1677,7 +1671,6 @@
 				486E8831220B78E4007CD915 /* CompositionLayer.swift in Sources */,
 				486E8832220B78E4007CD915 /* NullCompositionLayer.swift in Sources */,
 				25D5437422307C8B00ED90FA /* CompatibleAnimationView.swift in Sources */,
-				486E8833220B78E4007CD915 /* TextCompositionLayer.swift in Sources */,
 				486E8834220B78E4007CD915 /* SolidCompositionLayer.swift in Sources */,
 				486E8835220B78E4007CD915 /* PreCompositionLayer.swift in Sources */,
 				486E8836220B78E4007CD915 /* ImageCompositionLayer.swift in Sources */,
@@ -1795,7 +1788,6 @@
 				486E88A5220B78F4007CD915 /* PointValueProvider.swift in Sources */,
 				486E88A6220B78F4007CD915 /* CompositionLayer.swift in Sources */,
 				486E88A7220B78F4007CD915 /* NullCompositionLayer.swift in Sources */,
-				486E88A8220B78F4007CD915 /* TextCompositionLayer.swift in Sources */,
 				486E88A9220B78F4007CD915 /* SolidCompositionLayer.swift in Sources */,
 				486E88AA220B78F4007CD915 /* PreCompositionLayer.swift in Sources */,
 				486E88AB220B78F4007CD915 /* ImageCompositionLayer.swift in Sources */,
@@ -1935,7 +1927,6 @@
 				486E891F220B78FF007CD915 /* CompositionLayer.swift in Sources */,
 				486E8920220B78FF007CD915 /* NullCompositionLayer.swift in Sources */,
 				25D5437522307C8C00ED90FA /* CompatibleAnimationView.swift in Sources */,
-				486E8921220B78FF007CD915 /* TextCompositionLayer.swift in Sources */,
 				486E8922220B78FF007CD915 /* SolidCompositionLayer.swift in Sources */,
 				486E8923220B78FF007CD915 /* PreCompositionLayer.swift in Sources */,
 				486E8924220B78FF007CD915 /* ImageCompositionLayer.swift in Sources */,
@@ -2053,7 +2044,6 @@
 				486E8993220B790E007CD915 /* PointValueProvider.swift in Sources */,
 				486E8994220B790E007CD915 /* CompositionLayer.swift in Sources */,
 				486E8995220B790E007CD915 /* NullCompositionLayer.swift in Sources */,
-				486E8996220B790E007CD915 /* TextCompositionLayer.swift in Sources */,
 				486E8997220B790E007CD915 /* SolidCompositionLayer.swift in Sources */,
 				486E8998220B790E007CD915 /* PreCompositionLayer.swift in Sources */,
 				486E8999220B790E007CD915 /* ImageCompositionLayer.swift in Sources */,
`

But when pod install I still meet another problem:

`The Swift pod `lottie-react-native` depends upon `React-Core`, `React-DevSupport`, `React-RCTActionSheet`, `React-RCTAnimation`, `React-RCTBlob`, `React-RCTImage`, `React-RCTLinking`, `React-RCTNetwork`, `React-RCTSettings`, `React-RCTText`, `React-RCTVibration`, `React-RCTWebSocket`, `Folly`, `React-cxxreact`, `React-jsiexecutor`, `yoga`, `React-fishhook`, `DoubleConversion`, `glog`, `React-jsinspector`, and `React-jsi`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

Follow the guide to use 3.0.2 and lottie-ios 3.0.3.

**Comment by leekeunhwan** [comment]
I am also experiencing same issues @alimek

RN Version: 0.59.10

```
<unknown>:0: error: filename "TextCompositionLayer.swift" used twice: '/Users/${userName}/${packageName}/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift' and '/Users/${userName}/${packageName}/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by ashnfb** [comment]
If use_modular_headers isn't compatible with your pod file, try use_frameworks instead

**Comment by ganoch** [comment]
> I have different problem:
> 
> ```
> unknown>:0: error: filename "TextCompositionLayer.swift" used twice: 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift' and 'XXX/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift'
> <unknown>:0: note: filenames are used to distinguish private declarations with the same name
> ```
> 
> I have linked the `ios-lottie` and `lottie-react-native` manually

you ever fix this issue? facing the same issue

**Comment by alimek** [comment]
@ganoch nope, just downgraded to `2.6.1`

**Comment by ganoch** [comment]
@alimek I just deleted and removed every instance of lottie on my setup, including previous manually set up lottie libraries, then relinked and pod installed and then it worked

I think I should have removed all manual references before reinstalling the new version.

**Comment by pianoman730** [comment]
@alimek What was the process you took to install 2.6.1? I had similar issues installing 3.0.x.

**Comment by LPranulis** [comment]
@pianoman730 , @alimek , @ganoch see this: #523

**Comment by ganoch** [comment]
there is definitely cache issue somewhere here, after deleting DerivedData the problem reappeared

**Comment by mateomarin** [comment]
I am currently executing the exact installation steps in the README using RN 0.60.4. Autolinking apparently does not work, because the pod paths for lottie-ios and lottie-react-native don't appear in the Podfile, so I linked them manually. Following that, I tried running react-native run-ios, but there seems to be a module map problem.. more specifically:

fatal error: module map file '...Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found

What is the latest stable version of RN/Lottie-ios/Lottie-React-Native that you guys were able to make the lib work with?

**Comment by mateomarin** [comment]
Ok. Made it work in RN 0.60.4, somehow. I don't know if it was just lucky or replicable, I've been at it for the good part of the last 7h.. I'm going to go step-by-step...

1. yarn add lottie-react-native

2. yarn add lottie-ios@3.0.3

3. Copy and pasted the following lines in the Podfile (DO NOT USE react native link)
pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

4. In the XCode Project ONLY added the Lottie.xcodeproj from the node_modules/lottie into the Libraries folder - DO NOT add the node_modules/lottie-react-native xcodeproj as well as a Library, as indicated by some comments.

5. In the project's ios folder (cd ios), run pod install.

6. react-native run-ios

Just that. Before, I tried practically every solution posted til now, including the empty swift file, bridging header, PATH  and other solutions. Nothing worked. This magically did the trick. Hope it helps. Cheers.

**Comment by ganoch** [comment]
@mateomarin  the `"TextCompositionLayer.swift" used twice` I think I solved by upgrading to lottie-ios@3.0.6 

OR i haven't tried it yet, but @tokinonagare's patch should work, combined with `patch-packager` should be enough for a short while until 3.0.6 is officially supported

**Comment by tareqdayya** [comment]
Same here, stuck at pod install/build. After getting stuck the same way @pianoman730  did, I tried adding the lottie.framework to embedded binaries and I now have one error preventing me from the build:
 "TextCompositionLayer.swift" used twice, which @ganoch also had, but upgrading the lottie-ios did not fix it.
I have also tried the creation of a swift file to bring forth the creation of bridging headers. I have also tried adding the paths to the Library Search Paths.
Android installs fine, but the animation never starts (it displays nothing but the last frame.)

**Comment by ganoch** [comment]
@tareqdayya how did you update to 3.0.6? I had to use github source because 3.0.6 was not on npmjs 

```
...
    "lottie-ios": "github:airbnb/lottie-ios#3.0.6",
...
```

**Comment by tareqdayya** [comment]
@ganoch When I didn't find it, I upgraded to the latest. I have just tried what you did as well and problem is still there.

**Comment by mynamespace** [comment]
I don't know if it's a coincidence, but the "CocoaPods could not find compatible versions for pod "lottie-ios"" error is gone updating cocoapods... seems like I had an old version.
`sudo gem install cocoapods`

**Comment by rodrigowpl** [comment]
Same issue here

issue when run pod install
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React-Core`, `React-DevSupport`, `React-RCTActionSheet`, `React-RCTAnimation`, `React-RCTBlob`, `React-RCTImage`, `React-RCTLinking`, `React-RCTNetwork`, `React-RCTSettings`, `React-RCTText`, `React-RCTVibration`, `React-RCTWebSocket`, `Folly`, `React-cxxreact`, `React-jsiexecutor`, `yoga`, `React-fishhook`, `DoubleConversion`, `glog`, `React-jsinspector`, and `React-jsi`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

Infos
```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 786.64 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

My podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'mereomob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mereomob
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!

end

```

Any idea?  thanks

**Comment by rodrigowpl** [comment]
Update: I've just updated `cocoapods` and works normally, as @mynamespace said

**Comment by nartjie101** [comment]
> I don't know if it's a coincidence, but the "CocoaPods could not find compatible versions for pod "lottie-ios"" error is gone updating cocoapods... seems like I had an old version.
> `sudo gem install cocoapods`

It worked. Thanks :)

**Comment by tareqdayya** [comment]
I can confirm that updating CocoaPods made the issue that arises during the pod install phase disappear. 
I only had to create a bridging header file afterwards to get everything to work.

**Comment by MaRuifeng** [comment]
I am able to get below versions to compatibly work in iOS.
- RN: 0.60.0
- lottie-ios: 3.0.3
- lottie-react-native: 3.1.0,
- Xcode: 10.3

1. Run `npm i --save lottie-react-native` and `npm i --save lottie-ios@3.0.3`
2. Add below pod dependencies to the `Podfile` under the `ios` folder
```
pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
```
3. Run `pod install` under the `ios` folder
4. Add a dummy empty swift file for compilation success as suggested [here](https://stackoverflow.com/a/54586937/4993386)
5. Change to XCode legacy build system as suggested [here](https://stackoverflow.com/q/52401856/4993386)

Now `react-native run-ios` should work with Lottie animations properly presented in the app.

**Comment by alfruiz** [comment]
for me it was only adding the swift dummy file as @MaRuifeng  told, step 4

**Comment by JimTeva** [comment]
> I guess I should mention I'm on RN 0.59, "lottie-ios": "^3.0.3", and "lottie-react-native": "^3.0.1",
> I'm getting this still:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "lottie-ios":
>   In Podfile:
>     lottie-ios (from `../node_modules/lottie-ios`)
> 
>     lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
>       lottie-ios (~> 3.0.4)
> ```
> 
> I then change this
> `pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
> to
> `pod 'lottie-ios', '~> 3.0.4'`
> and get this:
> 
> ```
> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
> The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
> To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
> you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> ```
> 
> Putting `:modular_headers => true` on `pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'` gives the same error.
> Putting `use_modular_headers!` at the top of the pod file, `pod install` runs successfully. But when I build it, I get additional errors:
> 
> ```
> Import of module 'glog.glog.log_severity' appears within namespace 'google'
> ```
> 
> I then tried what was described [here](https://www.gitmemory.com/issue/google/glog/393/465974652) and got this:
> 
> ```
> Declaration of 'RCTImageLoaderCancellationBlock' must be imported from module 'React.RCTGIFImageDecoder' before it is required
> ```
> 
> And that's where I'm stuck.

@pianoman730, Following @mynamespace advice, updating cocoapods solve the issue! Yay thanks @mynamespace

**Comment by alisherakb** [comment]
> > I guess I should mention I'm on RN 0.59, "lottie-ios": "^3.0.3", and "lottie-react-native": "^3.0.1",
> > I'm getting this still:
> > ```
> > [!] CocoaPods could not find compatible versions for pod "lottie-ios":
> >   In Podfile:
> >     lottie-ios (from `../node_modules/lottie-ios`)
> > 
> >     lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
> >       lottie-ios (~> 3.0.4)
> > ```
> > 
> > 
> > I then change this
> > `pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
> > to
> > `pod 'lottie-ios', '~> 3.0.4'`
> > and get this:
> > ```
> > [!] The following Swift pods cannot yet be integrated as static libraries:
> > 
> > The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
> > To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
> > you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> > ```
> > 
> > 
> > Putting `:modular_headers => true` on `pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'` gives the same error.
> > Putting `use_modular_headers!` at the top of the pod file, `pod install` runs successfully. But when I build it, I get additional errors:
> > ```
> > Import of module 'glog.glog.log_severity' appears within namespace 'google'
> > ```
> > 
> > 
> > I then tried what was described [here](https://www.gitmemory.com/issue/google/glog/393/465974652) and got this:
> > ```
> > Declaration of 'RCTImageLoaderCancellationBlock' must be imported from module 'React.RCTGIFImageDecoder' before it is required
> > ```
> > 
> > 
> > And that's where I'm stuck.
> 
> @pianoman730, Following @mynamespace advice, updating cocoapods solve the issue! Yay thanks @mynamespace

It doesn't in my case. Stuck on 
```The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.```

**Comment by JimTeva** [comment]
It works for me with this config:

lottie-ios: 3.0.3
lottie-react-native: ^3.1.0
react: 16.8.6,
react-native: 0.60.4,

1)
```
yarn add lottie-react-native
yarn add lottie-ios@3.0.3
```
2) Xcode: added a new Swift file and a Brigde header in the project folder
3) **Updated cocoapods**
4) In ios folder: `pod install`

**Comment by samitha9125** [comment]
no luck even after the cocoapod update. Does anyone know how to solve this issue?

lottie-ios: 3.0.3
lottie-react-native: ^3.1.0
RN 0.59.10

    The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
    To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
    you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by samitha9125** [comment]
> > > I guess I should mention I'm on RN 0.59, "lottie-ios": "^3.0.3", and "lottie-react-native": "^3.0.1",
> > > I'm getting this still:
> > > ```
> > > [!] CocoaPods could not find compatible versions for pod "lottie-ios":
> > >   In Podfile:
> > >     lottie-ios (from `../node_modules/lottie-ios`)
> > > 
> > >     lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
> > >       lottie-ios (~> 3.0.4)
> > > ```
> > > 
> > > 
> > > I then change this
> > > `pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
> > > to
> > > `pod 'lottie-ios', '~> 3.0.4'`
> > > and get this:
> > > ```
> > > [!] The following Swift pods cannot yet be integrated as static libraries:
> > > 
> > > The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
> > > To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
> > > you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> > > ```
> > > 
> > > 
> > > Putting `:modular_headers => true` on `pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'` gives the same error.
> > > Putting `use_modular_headers!` at the top of the pod file, `pod install` runs successfully. But when I build it, I get additional errors:
> > > ```
> > > Import of module 'glog.glog.log_severity' appears within namespace 'google'
> > > ```
> > > 
> > > 
> > > I then tried what was described [here](https://www.gitmemory.com/issue/google/glog/393/465974652) and got this:
> > > ```
> > > Declaration of 'RCTImageLoaderCancellationBlock' must be imported from module 'React.RCTGIFImageDecoder' before it is required
> > > ```
> > > 
> > > 
> > > And that's where I'm stuck.
> > 
> > 
> > @pianoman730, Following @mynamespace advice, updating cocoapods solve the issue! Yay thanks @mynamespace
> 
> It doesn't in my case. Stuck on
> 
> ```
> 
> The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
> To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
> you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.```
> ```

Same here. Still same error occurs even after updating cocoapods to 1.7.5. Did you find a solution?

**Comment by adamivancza** [comment]
I was able to make it work using patch-package lib. I've patched the xcodeproj file.:

install the patch-package lib to dev dependencies: `npm i patch-package --save-dev` or `yarn add patch-package postinstall-postinstall --dev`

edit your package.json file and add `patch-package` to postinstall:
`"scripts": {
 "postinstall": "patch-package"
 }`

create a patches folder, and create an empty file in it called 'lottie-ios+3.0.3.patch' and copy paste this: https://gist.github.com/adamivancza/bc75187ad4d11f1275020c6b4051316c

now when you run npm or yarn install you should see a following message:
patch-package 6.1.2
Applying patches...
lottie-ios@3.0.3 ✔

**Comment by calix** [comment]
Creating the bridge header file solved the issue for me.

**Comment by artyorsh** [comment]
> @emilioicai
> After upgrade to 3.0.2, the error still exists… 😭
> 
> ```
> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
> The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> ```
> 
> RN version: 0.59.10
> lottie-react-native: 3.0.2

For anyone facing this issue - try updating your podfile with `use_frameworks!`. This should fix this issue since lottie v3 is written in Swift. [Here is a detailed explanation](https://stackoverflow.com/a/41210375/10434654)

**Comment by artyorsh** [comment]
@calix can you give more details please?

**Comment by MacKentoch** [comment]
> iOS install works for me with this config:
> 
> lottie-ios: 3.0.3
> lottie-react-native: ^3.1.0
> react: 16.8.6,
> react-native: 0.60.4,
> 
> 
> ```
> yarn add lottie-react-native
> yarn add lottie-ios@3.0.3
> ```
> 
> 1. Xcode: added a new Swift file and a Brigde header in the project folder
> 2. **Updated cocoapods**
> 3. In ios folder: `pod install`
> 
> (no modification in Podfile)

**NOTE: manually adding a bridging header file:**
- Add a new file to Xcode (`File > New > File`), then select `Source`and click `Header File`.
- Name your file `YourProjectName-Bridging-Header.h` (*Change `YourProjectName` to your real project name* 😉)

**Comment by MacKentoch** [comment]
> iOS install works for me with this config:
> 
> lottie-ios: 3.0.3
> lottie-react-native: ^3.1.0
> react: 16.8.6,
> react-native: 0.60.4,
> 
> 
> ```
> yarn add lottie-react-native
> yarn add lottie-ios@3.0.3
> ```
> 
> 1. Xcode: added a new Swift file and a Brigde header in the project folder
> 2. **Updated cocoapods**
> 3. In ios folder: `pod install`
> 
> (no modification in Podfile)

**NOTE: creating bridging header _easy and fast way_:**

- in xcode: add new file -> add new `Swift file` and name it anything you want like for example `dummy.swift`.
- then valid and xcode will ask you wether you want to create a bridging-header file. Say yes.
- you can delete the swift file `dummy.swift` and now

**Comment by MehranTheDeveloper** [comment]
```
lottie-ios: 3.0.3
lottie-react-native: ^3.1.0
react: 16.8.6,
react-native: 0.60.4,
```
First Update cocoapods with command 

`sudo gem install cocoapods`

Then following Error coming 

**"NameError - uninitialized constant Concurrent::Promises"**

Fix with [link](https://github.com/CocoaPods/CocoaPods/issues/8991) . Run Command

`sudo gem install concurrent-ruby`

Then following errors are coming

```
ld: directory not found for option '-L/Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/ios/build/dsPlayground/Build/Products/Debug-iphonesimulator/React'
⚠️  ld: directory not found for option '-L/Users/lyqht/Documents/react-native-mol-design-system/dsPlayground/ios/build/dsPlayground/Build/Products/Debug-iphonesimulator/yoga'
⚠️  ld: Could not find auto-linked library 'swiftCoreFoundation'
⚠️  ld: Could not find auto-linked library 'swiftQuartzCore'
⚠️  ld: Could not find auto-linked library 'swiftCore'
⚠️  ld: Could not find auto-linked library 'swiftCoreGraphics'
⚠️  ld: Could not find auto-linked library 'swiftObjectiveC'
⚠️  ld: Could not find auto-linked library 'swiftDispatch'
⚠️  ld: Could not find auto-linked library 'swiftSwiftOnoneSupport'
⚠️  ld: Could not find auto-linked library 'swiftDarwin'
⚠️  ld: Could not find auto-linked library 'swiftUIKit'
⚠️  ld: Could not find auto-linked library 'swiftCoreImage'
⚠️  ld: Could not find auto-linked library 'swiftFoundation'
⚠️  ld: Could not find auto-linked library 'swiftMetal'
⚠️  ld: Could not find auto-linked library 'swiftCoreLocation'

```

Fix by adding "$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)" to the library search paths of your target , See [link](https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios/53101587#)

**Comment by mobigaurav** [comment]
Had the same issue, Problem got resolved when I ran the command 
1) pod repo update
2) pod install in iOS folder
<img width="967" alt="lottie" src="https://user-images.githubusercontent.com/8948442/66013802-922c8b00-e49a-11e9-8128-fd249bf57c90.png">

**Comment by schumannd** [comment]
what solved a similar error for me was [creating an empty swift file in xcode](https://stackoverflow.com/a/56176956/1175081)

**Comment by seblau** [comment]
> I guess I should mention I'm on RN 0.59, "lottie-ios": "^3.0.3", and "lottie-react-native": "^3.0.1",
> I'm getting this still:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "lottie-ios":
>   In Podfile:
>     lottie-ios (from `../node_modules/lottie-ios`)
> 
>     lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.0.1, which depends on
>       lottie-ios (~> 3.0.4)
> ```
> 
> I then change this
> `pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
> to
> `pod 'lottie-ios', '~> 3.0.4'`
> and get this:
> 
> ```
> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
> The Swift pod `lottie-react-native` depends upon `React`, which does not define modules. 
> To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
> you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> ```
> 
> Putting `:modular_headers => true` on `pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'` gives the same error.
> Putting `use_modular_headers!` at the top of the pod file, `pod install` runs successfully. But when I build it, I get additional errors:
> 
> ```
> Import of module 'glog.glog.log_severity' appears within namespace 'google'
> ```
> 
> I then tried what was described [here](https://www.gitmemory.com/issue/google/glog/393/465974652) and got this:
> 
> ```
> Declaration of 'RCTImageLoaderCancellationBlock' must be imported from module 'React.RCTGIFImageDecoder' before it is required
> ```
> 
> And that's where I'm stuck.

@JakeHadley: I am getting the same issue, see: https://github.com/react-native-community/react-native-maps/issues/3209

**Comment by LoRaetz** [comment]
> If use_modular_headers isn't compatible with your pod file, try use_frameworks instead

thanks bud, works perfectly now

**Comment by pvanny1124** [comment]
> Adding `use_modular_headers!` to the podfile allows the pods to be installed correctly. Thanks again @mysport12

this worked for me, thanks!

**Comment by Navicna** [comment]
Updating lottie solved for me.

**Comment by prog-24** [comment]
Upgrading xCode always seem to throw ten spanners in the works. Tried everything here to no avail, anyone with any other ideas. I am stuck.

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.

**Comment by flikQ** [comment]
> I'm closing this as a version update should solve this issue.

Which version of which library should solve this?

**Comment by emilioicai** [comment]
lottie-react-native 4.0.2

**Comment by flikQ** [comment]
> lottie-react-native 4.0.2

I am using that version and still getting the following:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**Comment by ali14a** [comment]
Getting same error for 
"lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",

**Comment by ali14a** [comment]
it got fixed using https://github.com/facebook/react-native/issues/26217#issuecomment-536118532

**Comment by Bournegit** [comment]
Getting this error on version V4.0.2 
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

Any help.

**Comment by austinGENEreeve** [comment]
> Getting this error on version V4.0.2
> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
> The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> 
> Any help.

I got this same error and was able to solve it by updating my project from react native v0.63.2 to v064.2.

**Comment by AkshayAdiga1997** [comment]
Works fine with 
```
"react": "17.0.1",
"react-native": "0.64.2",
"lottie-ios": "3.1.8",
"lottie-react-native": "^3.1.0",
```
